### ISSUE TITLE
How to protect certain fields from displaying in the view

### ISSUE THREAD

**Issue by heyyadan** [lakshmaji/iadmin#2]
How can we hide the column of password and image?

**Comment by lakshmaji** [comment]
### Rendering Images 

Make sure the name of the column in the table must be imageUrl if the application is trying to store some sort of images.
For your reference, the below are the lines of code you can modify according to the requirement 

    https://github.com/lakshmaji/iadmin/blob/master/edit/index.php#L171
    https://github.com/lakshmaji/iadmin/blob/master/edit/index.php#L189

### Hiding Passwords

There is no such functionality to configure which fields have to be hidden or shown, but for now, we can do with some logic that resembles more like imageUrl handling
-    Verify if the field is protected while iterating through column names for the given table
*mysqli_fetch_fields* (line no 169)
```php
    $is_password = $v=="user_password"? true:false; 
```

 - Then add your own / required conditions to facilitate/match the requirements. In your case, we need to add the following code after line no 189

```php
   if($is_password) {
     continue; // what ever logic you  want to 
   }
```


Will try to add this functionality

**Comment by lakshmaji** [comment]
Similarly you can do with images also
```php
    $is_image = $v=="image_coulmn"? true:false; 
    if($is_image {
       continue; // what ever logic you  want to 
    }
```
